package uk.co.claritysoftware.exam.slammr.webapp.persistence.dynamodb.item.question

import com.amazonaws.annotation.Immutable
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted
import uk.co.claritysoftware.exam.slammr.webapp.persistence.dynamodb.convertor.ZonedDateTimeConverter
import java.io.Serializable
import java.time.ZonedDateTime

/**
 * Encapsulates the data for a Question dynamodb item
 */
@DynamoDBTable(tableName = "exam-slammr-questions")
@Immutable
data class QuestionItem(@field:DynamoDBHashKey
						@field:DynamoDBAutoGeneratedKey
						var id: String?,

						var slug: String,

						var summary: String,

						var questionText: String,

						var answers: List<AnswerDocument>,

						var tags: List<String>,

						var certifications: List<String>,

						var furtherReadings: List<FurtherReadingDocument>,

						var createdBy: String,

						@field:DynamoDBTypeConverted(converter = ZonedDateTimeConverter::class)
						var createdDateTime: ZonedDateTime,

						var updatedBy: String?,

						@field:DynamoDBTypeConverted(converter = ZonedDateTimeConverter::class)
						var updatedDateTime: ZonedDateTime?,

						var status: String,

						var votes: Int
) : Serializable