package uk.co.claritysoftware.exam.slammr.webapp.persistence.dynamodb.item.question

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted
import uk.co.claritysoftware.exam.slammr.webapp.persistence.dynamodb.convertor.ZonedDateTimeConverter
import java.io.Serializable
import java.time.ZonedDateTime

/**
 * Encapsulates the data for a Question dynamodb item
 */
@DynamoDBTable(tableName = "exam-slammr-questions")
data class QuestionItem(@DynamoDBHashKey
						@DynamoDBAutoGeneratedKey
						val id: String?,

						val slug: String,

						val summary: String,

						val questionText: String,

						val answers: List<AnswerDocument>,

						val tags: List<String>,

						val certifications: List<String>,

						val furtherReadings: List<FurtherReadingDocument>,

						val createdBy: String,

						@DynamoDBTypeConverted(converter = ZonedDateTimeConverter::class)
						val createdDateTime: ZonedDateTime,

						val updatedBy: String?,

						@DynamoDBTypeConverted(converter = ZonedDateTimeConverter::class)
						val updatedDateTime: ZonedDateTime?,

						val status: String,

						val votes: Int) : Serializable