server:
  port: 8888

spring:
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config/examSlammrRestUser, classpath:/config/examSlammrRestQuestion, classpath:/config/examSlammrWebapp